### ISSUE TITLE
Specify multiple API

### ISSUE THREAD

**Issue by YannickB** [crudlio/crudl#42]
Hello all,

First of all thank you for this wonderful project, I find the concept very interesting.

I have several micro/api-only services (one for manage users, another for managing products, etc...) and I'd like to unify their admin interface into a centralized one. This way we have both the flexibility of microservices and the comfort of a unique interface for administrators.

This is how I found crudl, and I believe it's a very good place to start, the only thing is it's look like we can specify only one api. Is there any way to specify several ? Do you believe this feature shall be on the roadmap ?

If not I think I'll just have to build a centralized API which will get together the other ones, so no real big deal, but I wanted to share my issue with you to know your thoughts.

Have a nice day!

**Comment by sehmaschine** [comment]
That´s definitely on the roadmap with a very high priority (I actually thought that we already implemented it). Thanks for bringing it up!

**Comment by vam** [comment]
@YannickB Hello and thanks for you comment! Good news: You can do that!

As of the crudl version 0.3.0, we're using [connectors](https://github.com/crudlio/crudl-connectors-base) to access the backend API. It's a very flexible and extensible way to access API endpoints. Each connector can point to a different URL.

This snippet is illustrates the basic idea:
```js
import { createFrontendConnector, createBackendConnector } from '@crudlio/crudl-connectors-base'
import { crudToHttp, url } from '@crudlio/crudl-connectors-base/lib/middleware'

function createConnector(urlPath) {
  return createFrontendConnector(createBackendConnector())
    .use(crudToHttp())
    .use(url(urlPath))
}

// This is your users connector:
export users = createConnector('http://users.someserver.com/api/v1/users')

// This is you products api:
export products = createConnector('http://products.someserver.com/api/v1/products')
```

**Comment by sehmaschine** [comment]
@vam Thanks for clarifying! I already thought that we did this, but couldn't exactly remember how it's supposed to work. Reminder for myself: Work on the docs!

**Comment by YannickB** [comment]
@vam Same thanks for clarification and for the awesome design :+1:
