### ISSUE TITLE
Shouldn't descriptor's normalize occur before field's normalize?

### ISSUE THREAD

**Issue by cusspvz** [crudlio/crudl#46]
I've been setting up a project with crudl and it is awesome, congrats! 

In the meantime, I've found something that i don't quite understand why you guys placed by that way.

I supposed this was the data flux from the `get` action to the VALUES form state:
`get` action > descriptor `normalize` > field `normalize` > field `getValue` > component state

I though it worked that way because it is labelled as `data converter from backend to frontend`, and  since the `save` flux works on a reverse way:
`save` action < descritor `denormalize` < field `denormalize` < field `getValue` < component state

But it seems that you guys only run the descriptor `normalize` **after** the field `normalize` and field `getValue`, which is hardly to understand. And also goes against on what the README states it does (`The normalization function prepares the data for the frontend`).

So the current flow is: 
`get` action > field `getValue` > field `normalize` > descriptor `normalize` > component state

IMHO, I don't think this is correct and I'll have to fork it and **fix** for my project. I just need to know if you guys think this is also incorrect and if you want me to PR it.

Thanks!

**Comment by sehmaschine** [comment]
good point. I tend to agree with your proposal. @vam can you please also take a look.

**Comment by vam** [comment]
@cusspvz That's a good point. I'm going to merge your pull request to crudl 0.4. Thank you for you input and efforts!

**Comment by cusspvz** [comment]
Awesome! Thanks for your attention guys!
