### ISSUE TITLE
Filters - query between two dates

### ISSUE THREAD

**Issue by ingin** [crudlio/crudl#61]
HI all, 

When i configure a field "date_min" ($gt) only, it works.
When i configure a field "date_max" ($lte) only, it works.

But when i try to fill both of these fields the "date_min" ($gt) doesn't work anymore.

Here is my listView
```javascript
listView.filters = {
	fields: [
		{
			name: 'date_min',
			label: 'Date min',
			field: 'Date',
		},
		{
			name: 'date_max',
			label: 'Date max',
			field: 'Date',
		},
		{
		    name: 'keyword',
		    label: 'Mot clé',
		    field: 'Search',
		    helpText: 'Entrez un mot clé'
		},

	]
};
```

And then my API routes config
```javascript
router.route('/seostats')
		.get(function (req, res) {
				// some code
				if (req.query.date_min) { query["datesearch"] = { "$gte": req.query.date_min }}
				if (req.query.date_max) { query["datesearch"] = { "$lt": req.query.date_max }}
				// some code
		});
```

**Comment by sehmaschine** [comment]
What exactly "doesn't work anymore"? Querying the API?

**Comment by ingin** [comment]
Hi sehmaschine,
Sorry for my english... Thank for your quick response. Actually, when i use criteria separtly (date_min OR date_max), it works but when i set both criteria (date_min AND date_max), then the date_min is correct.

Please find attached files to illustrate my problem

![date_min date_max ko](https://user-images.githubusercontent.com/4551229/37705313-e0aebdb4-2cfb-11e8-9ce7-6f13832045a1.png)
![date_max ok](https://user-images.githubusercontent.com/4551229/37705314-e0c581e8-2cfb-11e8-934c-848d2b932a7b.png)
![date_min ok](https://user-images.githubusercontent.com/4551229/37705315-e0dc0710-2cfb-11e8-90b4-22b7505fe625.png)

**Comment by ingin** [comment]
So,
date_max < 2018-03-18 => OK
date_min >= 2018-03-17 => OK
date_min && date_max => KO (as you can see, i got result from date 2018-0-16 :(

**Comment by ingin** [comment]
I got same results when i call the API via postman :(

**Comment by sehmaschine** [comment]
Then it's an issue with your API (and not with crudl), right?

**Comment by sehmaschine** [comment]
Looking at your code, it seems that you overwrite `query["datesearch"]` if `date_max` is given.

**Comment by sehmaschine** [comment]
```
if (req.query.date_min && req.query.date_max) { query["datesearch"] = { "$gte": req.query.date_min, "$lt": req.query.date_max }}
```

**Comment by ingin** [comment]
Oh i understand now - was not sure how to do it. Thanks a lot. It's works !
