### ISSUE TITLE
Event when CrudlIO is loaded

### ISSUE THREAD

**Issue by moseleyi** [crudlio/crudl#66]
Is there (or if not, can it be created) an event that would allow us to perform actions once the data is loaded and visualised? I would like to trigger some other JavaScript but only after the data has been rendered, is it possible?

**Comment by sehmaschine** [comment]
Using the get action doesn't help, does it?
https://github.com/crudlio/crudl#the-get-action

I assume you wanna react to something like `componentDidUpdate`, right?

**Comment by moseleyi** [comment]
But the get action will be pre-normalize right?, at first I wanted to change some of the components on the list, their position etc. Something that can't be done via CSS because it's deep in the main crudl.js file. 
In general I'm trying to dig deep into the crudl.js file to find any events we can trigger. For example when filters are applied - can we manually trigger it? For example after ENTER is pressed?
