### ISSUE TITLE
Main filter and  item-handler

### ISSUE THREAD

**Issue by moseleyi** [crudlio/crudl#68]
Correct me if I'm wrong but I'm assuming the item-handler (the link to changeView) is assigned to the field that has `main : true`, correct? And it also becomes a default sorting, what if I want those two features in separate fields? For my user view I would like `username` to be the item-handler but I have this column `last-seen`, which is basically when users have last logged in. This field is the most important as our staff will  do things most of the time to the active users. 

Let me know if that's something that could be done. 

Apologies for the amount of questions, but it's been great using CrudlIO with GraphQL and Sequelize so far and I can see a lot of potential!

**Comment by sehmaschine** [comment]
You can apply `sortable` for every field, see https://github.com/crudlio/crudl-example-express/blob/master/crudl-admin-graphql/admin/views/entries.js

`main` does not mean it is `sortable` by default (unless we have a bug here).

**Comment by moseleyi** [comment]
Ah yes you're right. It's the property `sorted` that specifies default sorting. Thanks
