### ISSUE TITLE
steps to execute

### ISSUE THREAD

**Issue by richabhuwania** [crudlio/crudl#74]
Can you please mention the steps in order to execute the program?

**Comment by sehmaschine** [comment]
Please take a look at the examples and the docs.

**Comment by DavidBabel** [comment]
Which is where ? I cannot find any documentation or example link anywhere.

**Comment by sehmaschine** [comment]
https://github.com/crudlio/crudl/blob/master/README.md
https://github.com/crudlio/crudl-example-django/blob/master/README.md
https://github.com/crudlio/crudl-example-express/blob/master/README.md
